### PR TITLE
Support for custom and multiple indices with caching and backwards compatibility.

### PR DESCRIPTION
**Pull request by shaqk**
## Change Description

Support for custom and multiple indices with caching and backwards compatibility.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by jeffreyssmith2nd** [comment]
Thanks for the contribution! Do you mind rebasing your branch against develop?

**Comment by brandonfancher** [comment]
Relates to #22.

Nice work, @shaqk! 

👏👏👏

**Comment by brandonfancher** [comment]
Also relates to https://github.com/EOSIO/ual-ledger/issues/23

**Comment by shaqk** [comment]
> Thanks for the contribution! Do you mind rebasing your branch against develop?

https://github.com/EOSIO/eosjs-ledger-signature-provider/pull/29

**Comment by jeffreyssmith2nd** [comment]
Closing in favor of #29

**Pull request closed without merging**
