### PR TITLE
 getAppConfiguration should return application version

### PR DESCRIPTION
**Pull request by tarassh**
getAppConfiguration should return `application version and arbitrary data flag` not boolean.

## API Changes
- [x] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by jeffreyssmith2nd** [comment]
Thanks for this! Can you rebase your branch on develop before we merge it?

**Comment by tarassh** [comment]
@jeffreyssmith2nd the patch is against develop branch

**Comment by jeffreyssmith2nd** [comment]
Right but since it looks like you created your patch off the master branch, it pulls merge commits from master back into develop which muddies up the commit history. By rebasing your patch against develop, that won't happen.

You should be able to just `git rebase origin/develop` and `git push origin patch-1 --force`.

**Comment by tarassh** [comment]
@jeffreyssmith2nd done

**Pull request closed without merging**
